
    - name: Install Docker
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - docker-ce
        - docker-ce-cli
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine
      become: yes

    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    # - name: Install device-mapper-persistent-data
    #   yum:
    #     name: device-mapper-persistent-data
    #     state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    # - name: Enable Docker Edge repo
    #   ini_file:
    #     dest: /etc/yum.repos.d/docer-ce.repo
    #     section: 'docker-ce-edge'
    #     option: enabled
    #     value: 0
    #   become: yes

    # - name: Enable Docker Test repo
    #   ini_file:
    #     dest: /etc/yum.repos.d/docer-ce.repo
    #     section: 'docker-ce-test'
    #     option: enabled
    #     value: 0
    #   become: yes

    - name: Install Docker
      yum:
        name: '{{ item }}'
        state: present
      with_items:
        - docker-ce-17.12.1.ce-1.el7.centos
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
