- name: Start Docker service
  service:
    name: docker
    state: stopped
    enabled: yes
  become: yes

- name: Creating the deamon file in /etc/docker floder.
  copy: 
     src: $pwd/docker_storage/files/daemon.json
     dest: /etc/docker/daemon.json
     mode: '0777'

- name: copy the script file to remote host
  copy:
     src: $pwd/docker_storage/files/myscript.sh
     dest: /root/myscript.sh
     mode: '0777'

- name: Execute the script
  command: sh /root/myscript.sh

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
